### ISSUE TITLE
Showing portrait image when the phone is in landscape

### ISSUE THREAD

**Issue by Tgo1014** [gogopop/CameraKit-Android#141]
The images is okay in portrait, but as soons as the phone is rotate, the image zooms and the preview became in the wrong orientation.
That's kinda a critical problem.

My phone is a Samsung A5 2017.

Portrait
![screenshot_20170728-144230](https://user-images.githubusercontent.com/8679058/28729623-77db1150-73a3-11e7-8d57-235c044b371f.png)

Landscape
![screenshot_20170728-144243](https://user-images.githubusercontent.com/8679058/28729622-77d9daa6-73a3-11e7-82a6-04c704e15d39.png)

**Comment by commonsguy** [comment]
@Tgo1014: I was running into the same problem, on a Google Pixel. The problem seems tied to `com.flurgle:camerakit:0.9.17`. If I use `com.flurgle:camerakit:0.9.18` (the latest on JCenter), the problem goes away.

**Comment by Tgo1014** [comment]
@commonsguy that indeed solved the issue. Thanks! But why in the main page the latest version is `com.flurgle:camerakit:0.9.17`?
