### ISSUE TITLE
Camera View is black

### ISSUE THREAD

**Issue by prasad456** [gogopop/CameraKit-Android#150]
Unable to view any thing from camera view. its just displaying black area

**Comment by kimihailv** [comment]
Did you call setFacing() or set up attribute ckFacing in xml?

**Comment by prasad456** [comment]
Yes, I'm calling before camera.start()

**Comment by xp-vit** [comment]
@prasad456 What is your phone model? I had such issue reported from users of OnePlus 5, however it works fine on OnePlus 3t.

**Comment by prasad456** [comment]
LG stylus 3 Android 7

**Comment by prasad456** [comment]
Your sample was working fine
but I integrated this library to my project. This issue raises?

**Comment by prasad456** [comment]
its working when i given a android:hardwareAccelerated="true" in application
