### ISSUE TITLE
don't make audio access mandatory

### ISSUE THREAD

**Issue by kerimovscreations** [gogopop/CameraKit-Android#171]
I use this library, just for image shooting and it keep's request audio permission. How can I disable this request?

**Comment by kerimovscreations** [comment]
I have found solution! Thanks for library

**Comment by developer--** [comment]
could you tell me your solution?

**Comment by kerimovscreations** [comment]
@developer--  you can find from documentation http://docs.camerakit.website/#/?id=ckpermissions
