### ISSUE TITLE
bug(focus): Tap to focus get immediately reset after focus 

### ISSUE THREAD

**Issue by DavidWiesner** [gogopop/CameraKit-Android#33]
Thanks for this nice library. I saw you recently added tap to focus and it worked like charm. 
But after tap to focus and the area got the focus, the focus immediately get lost after that. 

I notice in [Camera1.java#L466](https://github.com/flurgle/CameraKit-Android/blob/987d94645430e9e2b9a4de1c5fcad904d1ebd928/camerakit/src/main/api16/com/flurgle/camerakit/Camera1.java#L466) the focus mode will be reset immediately after the focus was set. It would be better to have some time to take a picture before the focus got lost. 

So you can add an handler to reset the focus after a period of time see [com/android/camera/Camera.java#835](https://android.googlesource.com/platform/packages/apps/Camera/+/838e6e75fdcb1946deef2fae276c03f2cb00e596/src/com/android/camera/Camera.java#835) for an example.

regards,
david

**Comment by dwillmc** [comment]
Now fixed, please update to `0.9.18`.
