### ISSUE TITLE
Make FocusMarkerLayout used in demo to be a part of library

### ISSUE THREAD

**Issue by xp-vit** [gogopop/CameraKit-Android#35]
I started testing Tap to focus and found implementation of FocusMarkerLayout to be rather useful and I think it probably would be a good idea to make it a part of library. Please share your opinion and if you are agree I'll be able to create pull request for this.

**Comment by ronaldo-getreveel** [comment]
Agreed!

**Comment by dwillmc** [comment]
This is in `0.9.16`, coming today. You'll be able to set tap mode to `tapWithMarker`.
