### ISSUE TITLE
Landscape preview and video capture

### ISSUE THREAD

**Issue by kevin-zqw** [gogopop/CameraKit-Android#38]
Hi, I'm working on an app which support landscape only. I want to use this awesome library to capture video in landscape mode.

But it seems that this library doesn't support landscape activity, the preview was rotated and distorted.

How to fix this issue?

**Comment by andreidiaconu** [comment]
Hi! I tried to fix a similar issue reported in the comments of #19 . Do you mind testing using #39 on your device? Thanks!

**Comment by kevin-zqw** [comment]
@andreidiaconu I tested your pull request #39 , it works perfect on my two test devices.

**Comment by andreidiaconu** [comment]
I am glad to hear that! There are still some issues with STILL mode, described in the PR comments on #39 which I will try to fix and hopefully the PR will be approved.
