### ISSUE TITLE
RECORD_AUDIO permission when used only for taking pictures

### ISSUE THREAD

**Issue by zoltanf** [gogopop/CameraKit-Android#46]
Hello. First of thx for this great library, it helps with the custom camera integrations immensely.

Is it possible somehow to set the camera to picture-only mode, and then not request the permission android.permission.RECORD_AUDIO? At the moment I see that in the code under requestCameraPermission() both android.permission.CAMERA and android.permission.RECORD_AUDIO are requested. This can be a problem if the user is expecting that the application is only taking pictures for example.

I can also do a PR if you think it's worth supporting such scenario, or otherwise the hosting activity can handle this before calling the .start().

**Comment by dwillmc** [comment]
There's a new attribute you can use called `ckPermissions`. Set it to `picture` to only handle the picture permission.

Coming later today in `0.9.16`.

**Comment by zoltanf** [comment]
Thank you!
