### ISSUE TITLE
Memory leak while recording video

### ISSUE THREAD

**Issue by jimmylilyy** [gogopop/CameraKit-Android#47]
Thanks for your cool project that saved a lot of my time.
I found a memory leak issue on recording video,  as the logs:

03-30 08:28:02.603: E/AudioFlinger(323): not enough memory for AudioTrack size=65600
03-30 08:28:02.603: D/MemoryDealer(323):   AudioTrack (0xab3f43b0, size=1048576)
03-30 08:28:02.603: D/MemoryDealer(323):     0: 0xab3f43c8 | 0x00000000 | 0x00010040 | A 
03-30 08:28:02.603: D/MemoryDealer(323):     1: 0xab3f4dc0 | 0x00010040 | 0x00010040 | A 
03-30 08:28:02.603: D/MemoryDealer(323):     2: 0xab4ab660 | 0x00020080 | 0x00001040 | A 
03-30 08:28:02.603: D/MemoryDealer(323):     3: 0xab3eceb8 | 0x000210C0 | 0x00010040 | A 
03-30 08:28:02.603: D/MemoryDealer(323):     4: 0xab3ecf88 | 0x00031100 | 0x00010040 | A 
03-30 08:28:02.603: D/MemoryDealer(323):     5: 0xab4ea978 | 0x00041140 | 0x00010040 | A 
03-30 08:28:02.603: D/MemoryDealer(323):     6: 0xab415d00 | 0x00051180 | 0x00010040 | A 
03-30 08:28:02.603: D/MemoryDealer(323):     7: 0xab49a0d8 | 0x000611C0 | 0x00010040 | A 
03-30 08:28:02.603: D/MemoryDealer(323):     8: 0xab3f04b0 | 0x00071200 | 0x00010040 | A 
03-30 08:28:02.603: D/MemoryDealer(323):     9: 0xab4af9a8 | 0x00081240 | 0x00010040 | A 
03-30 08:28:02.603: D/MemoryDealer(323):    10: 0xab501368 | 0x00091280 | 0x00010040 | A 
03-30 08:28:02.603: D/MemoryDealer(323):    11: 0xab59c7d8 | 0x000A12C0 | 0x00010040 | A 
03-30 08:28:02.603: D/MemoryDealer(323):    12: 0xab403700 | 0x000B1300 | 0x00010040 | A 
03-30 08:28:02.603: D/MemoryDealer(323):    13: 0xab403a60 | 0x000C1340 | 0x00010040 | A 
03-30 08:28:02.603: D/MemoryDealer(323):    14: 0xab667e78 | 0x000D1380 | 0x00010040 | A 
03-30 08:28:02.603: D/MemoryDealer(323):    15: 0xab648700 | 0x000E13C0 | 0x00010040 | A 
03-30 08:28:02.603: D/MemoryDealer(323):    16: 0xab713f60 | 0x000F1400 | 0x0000EC00 | F 
03-30 08:28:02.603: D/MemoryDealer(323):   size allocated: 988160 (965 KB)
03-30 08:28:02.603: E/AudioFlinger(323): createRecordTrack_l() initCheck failed -12; no control block?
03-30 08:28:02.603: E/AudioRecord(323): AudioFlinger could not create record track, status: -12

It caused native error that let camera not available utils you reboot your device.
**The mMediaRecorder.release() should be called in endVideo().**

**Comment by dwillmc** [comment]
This is fixed in `0.9.16`, coming later today. Thanks!
