### ISSUE TITLE
activity screenOrientation="landscape"   Preview distort

### ISSUE THREAD

**Issue by wangchengyan** [gogopop/CameraKit-Android#56]
in demo
step1 : in AndroidManifest.xml set MainActivity
            android:screenOrientation="landscape"

step2: in   activity_main.xml   set   CameraView   
                 android:layout_width="match_parent"
                 android:layout_height="1024dp"

run app -> Preview landscape orientation

if i removed configureTransform  methed in TextureViewPreview.java
my device the preview distort

please help me   thanks

**Comment by dwillmc** [comment]
Now fixed, please update to `0.9.18`.

**Comment by luongvo** [comment]
@dwillmc I was face this issue this morning, too fast, thank you 👍
