### ISSUE TITLE
Can't record videos longer than 14 seconds

### ISSUE THREAD

**Issue by cabflip** [gogopop/CameraKit-Android#62]
I've implemented CameraKit in my app and works great, the only problem I had was while recording videos of 30 seconds, more or less, the output video file lasts between 11 and 14 seconds. Any idea why? Sorry for any mistakes in my english.

Thanks in advance.

**Comment by ryancheu** [comment]
This is because 

`initMediaRecorder()` in Camera1.java sets a max file size of 50000 bytes. I'm not sure why it's there, I just removed it.

**Comment by dwillmc** [comment]
Are you using the latest version? No limitations are set on the mediarecorder anymore.

**Comment by cabflip** [comment]
Thanks for replying! I was using an older version, 0.9.15. Now it records without limitations as @dwillmc said.
