### ISSUE TITLE
Doesn't draw in XML preview (perhaps just add isInEditMode?)

### ISSUE THREAD

**Issue by smhk** [gogopop/CameraKit-Android#76]
For this amazing library: in Android Studio, if you <com.flurgle.camerakit.CameraView android:id="@+id/camera"/> in an xml layout, the preview can't draw it.

Perhaps, very simply make it (say) just render a square of purple, in the editor - with a line of code isInEditMode?

Thanks for the amazing library

![screenshot](https://cloud.githubusercontent.com/assets/3938526/25434899/c0db7b2c-2a53-11e7-9a80-68c7d5da97bc.png)

**Comment by lucasleon2107** [comment]
I have this problem too, did you solve it?
